### ISSUE TITLE
Add data initialization script

### ISSUE THREAD

**Issue by springframeworkguru** [springframeworkguru/mssc-beer-service#18]

**Comment by aliazani** [comment]
In recent version of spring boot and hibernate:
By default, data.sql scripts are now run before Hibernate is initialized. This aligns the behavior of basic script-based initialization with that of Flyway and Liquibase.
spring.jpa.defer-datasource-initialization=true

**Comment by TaherVora** [comment]
The property used in application.property file is now deprecated so use : spring.sql.init.mode=always instead.

**Comment by Oussama-HAT** [comment]
> In recent version of spring boot and hibernate: By default, data.sql scripts are now run before Hibernate is initialized. This aligns the behavior of basic script-based initialization with that of Flyway and Liquibase. spring.jpa.defer-datasource-initialization=true

you saved my life, because my app wasn't running after I added the  sql script and the problem was Beer table not found I found your comment and my app is running now
